#define	USE_IPV6_ADDRESSING	0

#if defined(USE_IPV6_ADDRESSING) && USE_IPV6_ADDRESSING == 1
#define ADDRESS_FAMILY		AF_INET6
#define	DEFAULT_SERVER_ADDRESS	"::1"
#define	STRUCT_SOCKADDR_SIZE	sizeof(struct sockaddr_in6)
#define	ADDRESS_STRING_LENGTH	INET6_ADDRSTRLEN
#else
#define ADDRESS_FAMILY		AF_INET
#define	DEFAULT_SERVER_ADDRESS	"127.0.0.1"
#define	STRUCT_SOCKADDR_SIZE	sizeof(struct sockaddr_in)
#define	ADDRESS_STRING_LENGTH	INET_ADDRSTRLEN
#endif

#define	DEFAULT_SERVER_PORT	6683

#define	LISTEN_BACKLOG		10

#define	BIND_INUSE_RETRY_SECS	5

#define	ENABLE_COLORS		1

#if defined(ENABLE_COLORS) && ENABLE_COLORS == 1
#define COLOR_RESET		"\033[0m"
#define	COLOR_BLACK		"\033[30m"
#define	COLOR_BOLD_BLACK	"\033[1;30m"
#define	COLOR_RED		"\033[31m"
#define	COLOR_BOLD_RED		"\033[1;31m"
#define	COLOR_GREEN		"\033[32m"
#define	COLOR_BOLD_GREEN	"\033[1;32m"
#define	COLOR_YELLOW		"\033[33m"
#define	COLOR_BOLD_YELLOW	"\033[1;33m"
#define	COLOR_BLUE		"\033[34m"
#define	COLOR_BOLD_BLUE		"\033[1;34m"
#define	COLOR_MAGENTA		"\033[35m"
#define	COLOR_BOLD_MAGENTA	"\033[1;35m"
#define	COLOR_CYAN		"\033[36m"
#define	COLOR_BOLD_CYAN		"\033[1;36m"
#define	COLOR_WHITE		"\033[37m"
#define	COLOR_BOLD_WHITE	"\033[1;37m"
#else
#define COLOR_RESET		""
#define	COLOR_BLACK		""
#define	COLOR_BOLD_BLACK	""
#define	COLOR_RED		""
#define	COLOR_BOLD_RED		""
#define	COLOR_GREEN		""
#define	COLOR_BOLD_GREEN	""
#define	COLOR_YELLOW		""
#define	COLOR_BOLD_YELLOW	""
#define	COLOR_BLUE		""
#define	COLOR_BOLD_BLUE		""
#define	COLOR_MAGENTA		""
#define	COLOR_BOLD_MAGENTA	""
#define	COLOR_CYAN		""
#define	COLOR_BOLD_CYAN		""
#define	COLOR_WHITE		""
#define	COLOR_BOLD_WHITE	""
#endif
#define	COLOR_NONE		""

#define	COLOR_ERROR		COLOR_BOLD_RED
#define	COLOR_PLAYER_IDLE	COLOR_GREEN
#define	COLOR_PLAYER_IN_GAME	COLOR_RED
#define	COLOR_PLAYER_AWAITING	COLOR_BLUE

#define MIN_USERNAME_LENGTH	3
#define	MAX_USERNAME_LENGTH	20
#define MAX_USERNAME_SIZE	MAX_USERNAME_LENGTH+1
#define USERNAME_ALLOWED_CHARS	\
	"abcdefghijklmnopqrstuvwxyz0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ_"

#define	MIN_UDP_PORT_NUMBER	1024
#define	MAX_UDP_PORT_NUMBER	65535

#define	WHO_STATUS_LENGTH	37
#define	WHO_STATUS_BUFFER_SIZE	WHO_STATUS_LENGTH+1

#define COMMAND_BUFFER_SIZE	100
#define UINT16_BUFFER_SIZE	10
#define	CELL_INPUT_BUFFER_SIZE	10

#define	HASHTABLE_SIZE		16

#define	SELECT_TIMEOUT_SECONDS	3
#define	PLAY_REQUEST_TIMEOUT	60
#define	IN_GAME_TIMEOUT		60

#define	GAME_TABLE_ROWS		6
#define	GAME_TABLE_COLS		6
#define	MIN_ROW_LETTER		'A'
#define	MAX_ROW_LETTER		MIN_ROW_LETTER + GAME_TABLE_ROWS - 1
#define	MIN_COL_NUMBER		1
#define	MAX_COL_NUMBER		MIN_COL_NUMBER + GAME_TABLE_COLS - 1
#define	SHIP_COUNT		7

#define	WATER_SYMBOL		COLOR_BLUE "#" COLOR_RESET
#define	SHIP_SYMBOL		COLOR_BOLD_GREEN "@" COLOR_RESET
#define	MISS_SYMBOL		COLOR_NONE "-" COLOR_RESET
#define	SUNK_SYMBOL		COLOR_BOLD_RED "X" COLOR_RESET
